FROM registry.access.redhat.com/ubi9/ubi:latest as builder

RUN uname -m

RUN mkdir /stage

RUN dnf install -y zlib openssl-devel git gcc

ENV PATH="/root/.cargo/bin:${PATH}"

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y --default-toolchain 1.80.1

RUN git clone https://github.com/trustification/scale-testing --depth 1

RUN cd loadtests && cargo build --release --bin loadtest
RUN install loadtests/target/release/loadtest /usr/local/bin/loadtest

ENTRYPOINT ["/usr/local/bin/loadtest"]
